'use strict';
/* ── CURSOR ── */
const $c=document.getElementById('cursor');
if($c){document.addEventListener('mousemove',e=>{$c.style.left=e.clientX+'px';$c.style.top=e.clientY+'px'});document.querySelectorAll('button,a,input,select,textarea,.prod-card,.ath-card,.ins-card,.testi-card,.pillar,.proj-card,.team-card').forEach(el=>{el.addEventListener('mouseenter',()=>$c.classList.add('big'));el.addEventListener('mouseleave',()=>$c.classList.remove('big'))});}
/* ── REVEAL ── */
const rObs=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');rObs.unobserve(e.target)}})},{threshold:.1});
function initReveal(){document.querySelectorAll('.r,.rs,.rfade').forEach(el=>{el.classList.remove('in');rObs.observe(el)})}
/* ── NAV ── */
function go(page){document.querySelectorAll('.page').forEach(p=>p.classList.remove('on'));document.querySelectorAll('.nav-links button').forEach(b=>b.classList.remove('active'));const pg=document.getElementById('page-'+page);if(pg)pg.classList.add('on');const nl=document.getElementById('nl-'+page);if(nl)nl.classList.add('active');window.scrollTo({top:0,behavior:'smooth'});setTimeout(initReveal,80);closeMobileNav();}
function toggleNav(){const l=document.querySelector('.nav-links');if(!l)return;if(l.dataset.open==='1'){closeMobileNav();}else{l.style.cssText='display:flex;flex-direction:column;position:absolute;top:58px;left:0;right:0;background:rgba(255,255,255,.96);padding:20px 24px;gap:18px;border-bottom:1px solid rgba(0,0,0,.07);backdrop-filter:blur(20px);z-index:599';l.dataset.open='1';}}
function closeMobileNav(){const l=document.querySelector('.nav-links');if(!l)return;if(window.innerWidth<=960)l.style.display='';l.dataset.open='0';}
window.addEventListener('resize',()=>{if(window.innerWidth>960){const l=document.querySelector('.nav-links');if(l)l.style.cssText=''}});
/* ── TABS ── */
function aTab(name,btn){document.querySelectorAll('.tab-pane').forEach(t=>t.classList.remove('on'));document.querySelectorAll('.atab').forEach(t=>t.classList.remove('on'));const p=document.getElementById('tab-'+name);if(p)p.classList.add('on');if(btn)btn.classList.add('on');}
/* ── PILLS ── */
document.addEventListener('click',e=>{const pill=e.target.closest('.fpill');if(!pill)return;pill.parentElement.querySelectorAll('.fpill').forEach(p=>p.classList.remove('on'));pill.classList.add('on');});
/* ── PROFILE PREVIEW ── */
const pd={};
function upPrev(el,k){pd[k]=el.value;const fn=pd.fn||'Athlete',ln=pd.ln||'Name';const nameEl=document.getElementById('pv-name');if(nameEl)nameEl.textContent=fn+' '+ln;const avEl=document.getElementById('pv-av');if(avEl){const ini=((fn[0]||'')+(ln[0]||'')).toUpperCase();avEl.textContent=ini||'🏃';avEl.style.fontSize=ini?'18px':'24px';}const s=(id,v)=>{const el=document.getElementById(id);if(el)el.textContent=v;};s('pv-handle',pd.ig||'@handle');s('pv-loc',(pd.st||'State')+' · '+(pd.cat||'Category'));s('pv-pb',pd.pb||'—');s('pv-age',pd.age||'—');s('pv-gear',pd.gear||'Amentum Gear');}
function doEnroll(){if(!pd.fn&&!pd.ln){toast('Please enter your name to continue.');return;}if(!pd.ig){toast('Please enter your Instagram handle.');return;}toast('Enrollment submitted! We\'ll verify @amentum.sports follow and confirm within 48 hours. Welcome to Amentum Sports 🎯');}
/* ── TOAST ── */
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3600);}
/* ── CHATBOT KB ── */
const KB={
greet:`Hi! 👋 Welcome to Amentum Sports — the largest javelin store in Asia.\n\nI can help with javelins, pricing, training, athlete enrollment, and orders. What would you like to know?`,
products:`Our complete Amentum range:\n\n🥇 **The Nalwa** — 800g · 90m · Elite · ₹26,000\n🥈 **The Chhatrapati** — 800g · 90m · ₹18,200\n🏅 **Olympic Gold** — 600g · Women's · ₹14,300\n⚡ **Black Panther** — 600g · Training · ₹8,500\n💜 **Purple White** — 600g · Training · ₹7,800\n🔴 **Amentum Red** — 600g · Youth · ₹5,460\n⭐ **Gold Kids** — 500g · 50m · Schools · ₹4,900\n🌿 **Vayuj 400g** — Mini · Grassroots · ₹1,298\n🌿 **Vayuj 300g** — Mini · Special Olympics · ₹1,180\n\nAlso: **Nemeth, Nordic, Polanik** international brands. Contact us for pricing.`,
pricing:`INR pricing with **zero customs duties**:\n\n• ₹1,180 — Vayuj 300g\n• ₹1,298 — Vayuj 400g\n• ₹4,900 — Gold Kids\n• ₹5,460 — Amentum Red\n• ₹7,800 — Purple White\n• ₹8,500 — Black Panther\n• ₹14,300 — Olympic Gold\n• ₹18,200 — The Chhatrapati\n• ₹26,000 — The Nalwa\n\nFor Nemeth/Nordic/Polanik: wa.me/+19084622069`,
shipping:`Yes! **Pan-India shipping** with zero customs duties on all Amentum products.\n\nThis saves you 15–30% vs competitors who pass on import duties.\n\nFor bulk/institutional orders, dedicated logistics support is available.\n\n📞 +91 9827654830 · wa.me/+19084622069`,
enroll:`To enroll as an Amentum athlete:\n\n1️⃣ Follow **@amentum.sports** on Instagram\n2️⃣ Open the **Athlete Arena** tab above\n3️⃣ Click **Enroll Now** and complete your profile\n4️⃣ Include PB, State, Category, age, current gear\n\nTop 3 monthly performers get **gear discounts** and national scouting visibility!`,
training:`World-class training from Amentum:\n\n🎯 **Online Plans** — video analysis, personalised technique correction\n🏟️ **Workshops** — across India (Goa, Delhi, and more)\n📊 **Video Feedback** — from Tom Petranoff & Pierre Beaudoin\n\nRohit Yadav became **Youth National Champion 2018 & World No.1 U18** through our online programme.\n\nContact us to join or host a workshop.`,
coaches:`Our world-class coaches:\n\n👤 **Tom Petranoff** (USA)\n— 2× Javelin World Record Holder\n— 3× Olympian\n— Inventor of the Turbojav system\n\n👤 **Pierre Beaudoin** (France)\n— French National Record Holder\n— Trained with Cuban National Team\n— IAAF (World Athletics) Consultant`,
team:`Amentum co-founders:\n\n👤 **Aditya Bhargava** — Masters Biomedical Engineering, UConn USA. Played tennis & cricket at university. Passionate about grassroots Indian sport.\n\n👤 **Siddharth Patil** — Represented India at Asia-Pacific Tchoukball 2010. Co-founded CoachKhoj. Headed IT & Strategy at Zee TAJ TV (Tensports).`,
special_olympics:`Yes! Amentum is the **Official Mini-Javelin Partner of Special Olympics India**.\n\nWe trained their coaches on the Mini-Javelin system for specially-abled athletes.\n\n**Vayuj 300g** is Special Olympics Bharat approved — safe, fun, and inclusive for all abilities.`,
nemeth:`We are the **authorised Indian distributor** for Nemeth Javelins (Hungary):\n\n• Nemeth Classic 85m — 800g\n• Nemeth Special 80m — 700g\n• Nemeth Club 85m — 800g\n• Nemeth Club 80m — 800g\n\nAlso Nordic & Polanik brands.\n📞 +91 9827654830 · wa.me/+19084622069`,
bulk:`Institutional bulk packages:\n\n📦 Starter — 10 units · ₹28,000\n📦 Academy — 25 units · ₹64,000\n📦 Elite — 50 units · ₹1,18,000\n\nIncludes onboarding + coach training. Custom packages available for schools, academies, NGOs.\n\n💬 wa.me/+19084622069`,
contact:`📞 **+91 9827654830**\n💬 **WhatsApp:** wa.me/+19084622069\n📸 **Instagram:** @amentum.sports\n📘 **Facebook:** facebook.com/amentumsports\n▶️ **YouTube:** @amentumsports5857\n🌐 **amentums.com**`,
default:`Great question! For the most accurate answer:\n\n💬 **WhatsApp:** wa.me/+19084622069\n📞 **+91 9827654830**\n📸 **Instagram:** @amentum.sports\n\nWe typically respond within a few hours!`
};
function getChatReply(msg){const m=msg.toLowerCase();if(m.match(/hi\b|hello|hey|namaste|good (morning|evening)/))return KB.greet;if(m.match(/product|all javelin|full list|what.*sell|models/))return KB.products;if(m.match(/price|cost|rupee|inr|₹|how much|rate/))return KB.pricing;if(m.match(/ship|deliver|dispatch|customs|pan.india/))return KB.shipping;if(m.match(/enroll|register|sign.?up|join.*arena|athlete arena/))return KB.enroll;if(m.match(/train|coaching|technique|improve|workshop.*train/))return KB.training;if(m.match(/coach|petranoff|beaudoin|world.record|olympian|iaaf/))return KB.coaches;if(m.match(/team|founder|aditya|siddharth|co.?founder|who.*start/))return KB.team;if(m.match(/special olympics|disable|specially.abled|para|vayuj/))return KB.special_olympics;if(m.match(/nemeth|nordic|polanik|international|distributor/))return KB.nemeth;if(m.match(/bulk|institution|academy.*order|school.*order|wholesale/))return KB.bulk;if(m.match(/contact|phone|whatsapp|number|email|reach/))return KB.contact;return KB.default;}
function addMsg(text,role){const msgs=document.getElementById('chat-msgs');const div=document.createElement('div');div.className='msg '+role;const now=new Date();const t=now.getHours().toString().padStart(2,'0')+':'+now.getMinutes().toString().padStart(2,'0');const fmt=text.replace(/\*\*(.*?)\*\*/g,'<strong>$1</strong>').replace(/\n/g,'<br>');div.innerHTML=`<div class="msg-bub">${fmt}</div><div class="msg-time">${t}</div>`;msgs.appendChild(div);msgs.scrollTop=msgs.scrollHeight;}
function showTyping(){const msgs=document.getElementById('chat-msgs');const d=document.createElement('div');d.id='typing-ind';d.className='msg bot';d.innerHTML='<div class="typing"><span></span><span></span><span></span></div>';msgs.appendChild(d);msgs.scrollTop=msgs.scrollHeight;}
function removeTyping(){const t=document.getElementById('typing-ind');if(t)t.remove();}
function sendMsg(){const inp=document.getElementById('chat-inp');const msg=inp.value.trim();if(!msg)return;inp.value='';addMsg(msg,'user');document.getElementById('chat-quick').style.display='none';showTyping();setTimeout(()=>{removeTyping();addMsg(getChatReply(msg),'bot')},800+Math.random()*700);}
function sendQ(msg){document.getElementById('chat-inp').value=msg;sendMsg();}
function openChat(preMsg){if(!chatOpen)toggleChat();if(preMsg)setTimeout(()=>{document.getElementById('chat-inp').value=preMsg;sendMsg();},450);}
let chatOpen=false,chatInited=false;
function toggleChat(){const win=document.getElementById('chat-win');chatOpen=!chatOpen;win.classList.toggle('open',chatOpen);if(chatOpen&&!chatInited){chatInited=true;setTimeout(()=>addMsg(KB.greet,'bot'),380);}if(chatOpen)setTimeout(()=>document.getElementById('chat-inp').focus(),350);}
document.addEventListener('DOMContentLoaded',()=>initReveal());
